name: Unit and Instrumentation Test
on: [push, pull_request]
jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          chmod +x ./gradlew
          sudo ./gradlew test
  android_tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [23, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: |
            chmod 755 ./gradlew
            ./gradlew connectedCheck
