name: Unit and Instrumentation Test
on: [push, pull_request]
jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          chmod +x ./gradlew
          sudo ./gradlew test
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          script: |
            chmod rwx ./gradlew
            ./gradlew connectedAndroidTest
