name: pr-all-tests
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Access ROOM_PASSPHRASE
        env:
          ROOM_PASSPHRASE: $
        run: echo ROOM_PASSPHRASE=\"ROOM_PASSPHRASE\" > ./local.properties

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Unit tests
        run: |
          chmod +x ./gradlew
          sudo ./gradlew test
